version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel-postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Give more privileges to the user
    command: postgres -c log_statement=all

  redis:
    image: redis:7-alpine
    container_name: hotel-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: hotel-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: h5EZlzbaBmZLL8NWf3M5assLtlIymAa3GbwyPd7oZpJ
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: