spring:
  application:
    name: Hotel Booking System
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true

  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 123
      driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changeset/changelog-master.yml

springdoc:
  swagger-ui:
      path: /swagger-ui.html

jwt:
  secret: h5EZlzbaBmZLL8NWf3M5assLtlIymAa3GbwyPd7oZpJ
  expiration: 86400000 # 24 hours in milliseconds
