spring:
  application:
    name: Hotel Booking System
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
      cache:
        type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changeset/changelog-master.yml
    default-schema: public

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    cache-names:
      - users
      - userProfile
      - hotels
      - rooms
      - hotelRooms
      - bookings
      - userBookings
      - hotelBookings
      - roomAvailability
      - roomDailyInventory
      - hotelReviews
      - userReviews
      - reviewByBooking
      - userPayments
      - hotelPayments
      - searchHotels
      - myHotels
    redis:
      time-to-live: 1800000          # Default TTL: 30 minutes (in milliseconds)
      cache-null-values: false
      use-key-prefix: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: h5EZlzbaBmZLL8NWf3M5assLtlIymAa3GbwyPd7oZpJ
  expiration: 86400000 # 24 hours in milliseconds